package appcast

import (
	"encoding/xml"
	"fmt"
	"regexp"
)

// A SparkleRSSFeedAppcast represents appcast for "Sparkle RSS Feed" that is
// generated by Sparkle Framework.
type SparkleRSSFeedAppcast struct {
	BaseAppcast
}

// A SparkleRSSFeedXML represents an RSS itself.
type SparkleRSSFeedXML struct {
	Items []SparkleRSSFeedXMLItem `xml:"channel>item"`
}

// A SparkleRSSFeedXMLItem represents an RSS item.
type SparkleRSSFeedXMLItem struct {
	Title                string                     `xml:"title"`
	MinimumSystemVersion string                     `xml:"minimumSystemVersion"`
	Enclosure            SparkleRSSFeedXMLEnclosure `xml:"enclosure"`
}

// A SparkleRSSFeedXMLEnclosure represents an RSS enclosure in item.
type SparkleRSSFeedXMLEnclosure struct {
	Version            string `xml:"version,attr"`
	ShortVersionString string `xml:"shortVersionString,attr"`
	URL                string `xml:"url,attr"`
}

// Uncomment uncomments XML tags in SparkleRSSFeedAppcast.Content.
func (a *SparkleRSSFeedAppcast) Uncomment() {
	if a.Content == "" {
		return
	}

	regex := regexp.MustCompile(`(<!--([[:space:]]*)?)|(([[:space:]]*)?-->)`)
	if regex.MatchString(a.Content) {
		a.Content = regex.ReplaceAllString(a.Content, "")
		return
	}
}

// ExtractReleases parses the content of the Sparkle RSS Feed from
// SparkleRSSFeedAppcast.Content and stores the extracted releases as an array
// in SparkleRSSFeedAppcast.Releases. Returns an error, if extracting was is
// unsuccessful.
func (a *SparkleRSSFeedAppcast) ExtractReleases() error {
	var x SparkleRSSFeedXML
	xml.Unmarshal([]byte(a.Content), &x)

	items := make([]Release, len(x.Items))
	for i, item := range x.Items {
		if item.Enclosure.ShortVersionString == "" {
			return fmt.Errorf("Version is required, but it's not specified for \"%d\" release", i+1)
		}

		r, err := NewRelease(item.Enclosure.ShortVersionString, item.Enclosure.Version)
		if err != nil {
			return err
		}

		r.DownloadURLs = []string{item.Enclosure.URL}
		items[i] = *r
	}

	a.Releases = items

	return nil
}
